import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-pink-100`}>
        <div className="flex flex-col gap-2">
          <NavBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
